<?php
if(isset($_SESSION['user']) && !empty($_SESSION['user'])){

    $connexion = mysqli_connect("localhost", "root", "", "blog");
    $username = $_SESSION['user']->username;
    $requete_head = "SELECT * FROM `utilisateurs` WHERE login = '$username'";
    $query_head = mysqli_query($connexion,$requete_head);
    $resultat_head = mysqli_fetch_all($query_head);
}
?>

<footer id="foot-container">
        <ul id="foot-ul-cont">
            <li class="foot-listyle"><a class="foot-lien" href="index.php">Accueil</a></li>
            <?php if(isset($_SESSION['user']) && $_SESSION['user']->droits == 1337 || $_SESSION['user']->droits == 42): ?>
            <li class="foot-listyle"><a class="foot-lien" href="cree-article.php">Créer un article</a></li>
            <?php endif; ?>
            <?php if(isset($_SESSION['user']) && $_SESSION['user']->droits == 1337): ?>
            <li class="foot-listyle"><a class="foot-lien" href="admin.php">Administration</a></li>
            <?php endif; ?>
            <?php if(!isset($_SESSION['user'])): ?>      
            <li class="foot-listyle"><a class="foot-lien" href="inscription.php">Inscription</a></li>
            <li class="foot-listyle"><a class="foot-lien" href="connexion.php">Connexion</a></li>
            <?php else : ?>
            <li class="foot-listyle"><a class="foot-lien" href="profil.php">Profil</a></li>
            <li class="foot-listyle"><a class="foot-lien" href="?disconnect">Déconnexion(<?=$_SESSION['user']->username; ?>)</a></li>
            <?php endif; ?>
        </ul>
        <p id="copyright">©opyright 2020 Coding School | Tous droits réservés | Projet réalisé par Amine, Clément et Serge.</p>
        <div id="vide">.</div>
    </footer>
</body>
</html>



