<?php
if(isset($_SESSION['user']) && !empty($_SESSION['user'])){

$connexion = mysqli_connect("localhost", "root", "", "blog");
$username = $_SESSION['user']->username;
$requete_head = "SELECT * FROM `utilisateurs` WHERE login = '$username'";
$query_head = mysqli_query($connexion,$requete_head);
$resultat_head = mysqli_fetch_all($query_head);

// var_dump($_SESSION);
}

$connexion = mysqli_connect("localhost", "root", "", "blog");

$requete_cat = "SELECT * FROM categories";
$query_cat = mysqli_query($connexion, $requete_cat);
$resultat_cat = mysqli_fetch_all($query_cat,MYSQLI_ASSOC);

// var_dump($resultat_cat);

?>

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="css/blog.css">
</head>
<body>
    <header id="head-container">
        <nav>
            <ul id="ul-container">
                <li class="head-li"><a class="head-lien" href="index.php">Accueil</a></li>
                <li id="dropdown" class="head-li">
                    <a class="head-lien" href="#">Catégories</a>
                    <ul id="ulofcat">
                        <?php foreach($resultat_cat as $cat): ?>
                            <li id="dropdown-child"><a href="articles.php?categorie=<?php echo $cat["id"] ?>&titre=<?php echo $cat["nom"] ?>&start=0"><?php echo $cat["nom"]; ?></a></li>
                        <?php endforeach; ?>
                    </ul>
                </li>
                <?php if(isset($_SESSION['user']) && $_SESSION['user']->droits == 1337 || $_SESSION['user']->droits == 42): ?>
                <li class="head-li"><a class="head-lien" href="creer-article.php">Créer un article</a></li>
                <?php endif; ?>
                <?php if(isset($_SESSION['user']) && $_SESSION['user']->droits == 1337): ?>
                <li class="head-li"><a class="head-lien" href="admin.php">Administration</a></li>
                <?php endif; ?>
                <?php if(!isset($_SESSION['user'])): ?>      
                <li class="head-li"><a class="head-lien" href="inscription.php">Inscription</a></li>
                <li class="head-li"><a class="head-lien" href="connexion.php">Connexion</a></li>
                <?php else : ?>
                <li class="head-li"><a class="head-lien" href="profil.php">Profil</a></li>
                <li class="head-li"><a class="head-lien" href="?disconnect">Déconnexion(<?=$_SESSION['user']->username; ?>)</a></li>
                <?php endif; ?>
            </ul>
        </nav>
    </header>